### PR TITLE
Further more features added, Kindly tell if any changes required

### PR DESCRIPTION
**Pull request by nikunj2001**
Added many new things i hope that you will like it. Do let me know if you need any further modifications.
Thanks

### CODE REVIEW

**Comment by babaiyu** [comment]
It's look good than before haha. I will merge this PR.

But did you know about [Lottie Web](https://github.com/airbnb/lottie-web)? Maybe it will be good for using animation for loading when transcode is started till end.

**Comment by nikunj2001** [comment]
I don't know about  Lottie Web but, i will definitely look into it....thanks!!!!!!!!
Do let me know if you need my help in any other project.
It was nice working on your project.
I must say your project is good.

**Comment by babaiyu** [comment]
Don't worry, you can learn it. I hope you have new experience while develop this project.
Thank you

**Comment by babaiyu** [comment]
If you have any trouble or idea, you can use Discussions on Github

**Pull request merged**
